server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/ql_thiet_bi
    password: 123456qQ@
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB
app:
  jwt:
    secret-key: daf66e01593f61a15b857cf433aae03a060703b2003e1149036bcc8dee755dbb
    expire-length: 2592000000 #30 days
